#!/usr/bin/env python3
"""Generate the web-side ontology modules from ``app/ontology/concepts.yaml``.

    uv run python scripts/gen_ontology.py           # (re)write the files
    uv run python scripts/gen_ontology.py --check   # exit 1 when any is stale

Writes (all under ``apps/web/src/lib/ontology/``):

    concepts.generated.ts   typed CONCEPTS / SOURCES / DOC_TYPES / FAMILIES /
                            PERIOD_TYPES / SUBORDINATE_NAMESPACES /
                            REGISTRY_VERSION
    reasons.generated.ts    REASONS — the 16 refusal codes with
                            {label, ui, explanation}
    concepts.snapshot.json  the registry exactly as GET /ontology/concepts
                            serves it

The output is a pure function of the YAML (no timestamps), so ``--check``
is a byte-for-byte comparison and runs in CI as the drift gate.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

WORKER_ROOT = Path(__file__).resolve().parents[1]
REPO_ROOT = WORKER_ROOT.parents[1]
WEB_ONTOLOGY_DIR = REPO_ROOT / "apps" / "web" / "src" / "lib" / "ontology"

if str(WORKER_ROOT) not in sys.path:
    sys.path.insert(0, str(WORKER_ROOT))

HEADER = (
    "// AUTO-GENERATED by apps/worker/scripts/gen_ontology.py from\n"
    "// apps/worker/app/ontology/concepts.yaml — DO NOT EDIT BY HAND.\n"
    "// Regenerate: cd apps/worker && uv run python scripts/gen_ontology.py\n"
    "// CI fails on drift: scripts/gen_ontology.py --check\n"
    "/* eslint-disable */\n\n"
)


def _ts(value: Any) -> str:
    """A JSON literal is a valid TS expression; keep keys quoted + stable."""
    return json.dumps(value, indent=2, ensure_ascii=False)


def _union(values: list[str]) -> str:
    return " | ".join(json.dumps(v) for v in values) if values else "never"


def render_concepts_ts(data: dict[str, Any]) -> str:
    concept_ids = list(data["concepts"].keys())
    source_ids = list(data["sources"].keys())
    out = [HEADER]
    out.append(f"export const REGISTRY_VERSION = {int(data['version'])} as const;\n\n")
    out.append(
        "export type Scope = 'annual' | 'ttm' | 'ytd' | 'quarterly' | 'monthly' | 'weekly' | 'unknown';\n"
    )
    out.append(
        "export type Basis =\n  | 'actual' | 'broker' | 'om_history' | 'market' | 'budget' | 'plan' | 'adjusted' | 'unknown';\n"
    )
    out.append(
        "export type ConceptUnit =\n  | 'usd' | 'pct' | 'ratio' | 'count' | 'keys' | 'date' | 'text' | 'index'\n"
        "  | 'usd_per_key' | 'usd_per_occupied_room' | 'years';\n"
    )
    out.append("export type ConceptSign = 'positive' | 'expense_positive' | 'signed';\n")
    out.append("export type ConceptPeriod = 'flow' | 'average' | 'point';\n")
    out.append("export type SourceKind = 'grounded' | 'assumption' | 'calculated' | 'override' | 'refusal';\n")
    out.append("export type ImpactBasis = 'noi' | 'revenue' | 'expense' | 'other';\n\n")
    out.append(f"export type ConceptId = {_union(concept_ids)};\n\n")
    out.append(f"export type SourceId = {_union(source_ids)};\n\n")
    out.append(f"export type DocType = {_union(list(data['doc_types']))};\n\n")
    out.append(
        "export interface ConceptAlias {\n"
        "  path: string;\n  basis: Basis | null;\n  scope: Scope | null;\n}\n\n"
        "export interface UsaliRef {\n  line: string;\n  section: string;\n  edition: number;\n}\n\n"
        "export interface FieldCatalogBinding {\n  namespace: string;\n  key: string;\n  percentage_key: boolean;\n}\n\n"
        "export interface VarianceConceptBinding {\n  key: string;\n  label: string;\n  impact_basis: ImpactBasis;\n}\n\n"
        "export interface WorksheetBinding {\n"
        "  row: string;\n  hist_key: string | null;\n  meta_key: string | null;\n  review_key: string | null;\n"
        "  override_key: string | null;\n  y1_src: 'expense' | 'fb' | 'revenue' | null;\n  y1_read: string[];\n"
        "  fmt: 'currency' | 'pct' | 'dollar';\n}\n\n"
        "export interface ScorerVariant {\n  basis: Basis | null;\n  scope: Scope | null;\n}\n\n"
        "export interface ConceptBindings {\n"
        "  field_catalog: FieldCatalogBinding | null;\n  critic_key: string | null;\n"
        "  variance_rule: string | null;\n  variance_concept: VarianceConceptBinding | null;\n"
        "  actuals_attr: string | null;\n  scorer_key: string | null;\n  scorer_synonyms: string[];\n"
        "  scorer_variants: Record<string, ScorerVariant>;\n  recognizer: string | null;\n"
        "  worksheet: WorksheetBinding | null;\n}\n\n"
        "export interface ConceptDef {\n"
        "  id: ConceptId;\n  label: string;\n  short: string;\n  group: string;\n  usali: UsaliRef | null;\n"
        "  unit: ConceptUnit;\n  sign: ConceptSign;\n  period: ConceptPeriod;\n"
        "  /** null only for point-in-time facts — see `note`. */\n  default_scope: Scope | null;\n"
        "  note: string | null;\n"
        "  identity: string | null;\n  identity_optional_terms: string[];\n  identity_tolerance: number;\n"
        "  usali_rules: string[];\n  engines: string[];\n  bindings: ConceptBindings;\n"
        "  /** Alias-map key → aliases. Keys are DocType values, family names (FAMILIES) or \"*\". */\n"
        "  aliases: Record<string, ConceptAlias[]>;\n  as_of: ConceptId | null;\n}\n\n"
        "export interface SourceDef {\n"
        "  label: string;\n  badge: string;\n  kind: SourceKind;\n  doc_types: DocType[];\n"
        "  explanation: string;\n  reason: string | null;\n}\n\n"
    )
    out.append(f"export const DOC_TYPES: readonly DocType[] = {_ts(data['doc_types'])};\n\n")
    out.append(f"export const FAMILIES: Record<string, DocType[]> = {_ts(data['families'])};\n\n")
    out.append(f"export const PERIOD_TYPES: Record<string, number> = {_ts(data['period_types'])};\n\n")
    out.append(
        f"export const SUBORDINATE_NAMESPACES: readonly string[] = {_ts(data['subordinate_namespaces'])};\n\n"
    )
    out.append(f"export const CONCEPT_IDS: readonly ConceptId[] = {_ts(concept_ids)};\n\n")
    out.append(f"export const CONCEPTS: Record<ConceptId, ConceptDef> = {_ts(data['concepts'])};\n\n")
    out.append(f"export const SOURCES: Record<SourceId, SourceDef> = {_ts(data['sources'])};\n")
    return "".join(out)


def render_reasons_ts(data: dict[str, Any]) -> str:
    codes = list(data["reasons"].keys())
    out = [HEADER]
    out.append(
        "/** One refusal code — why a value is a dash rather than a number. */\n"
        "export interface ReasonMeta {\n  label: string;\n  ui: string;\n  explanation: string;\n}\n\n"
    )
    out.append(f"export type ReasonCode = {_union(codes)};\n\n")
    out.append(f"export const REASON_CODES: readonly ReasonCode[] = {_ts(codes)};\n\n")
    out.append(f"export const REASONS: Record<ReasonCode, ReasonMeta> = {_ts(data['reasons'])};\n")
    # Phase 0.3 consumers (methodology page + tests) rely on these two helpers.
    out.append("\nexport const REFUSAL_GLYPH = '\u2014';\n")
    out.append("\nexport function isReasonCode(v: unknown): v is ReasonCode {\n  return typeof v === 'string' && (REASON_CODES as readonly string[]).includes(v);\n}\n")
    return "".join(out)


def render_snapshot(data: dict[str, Any]) -> str:
    return json.dumps(data, indent=2, ensure_ascii=False) + "\n"


def render_all() -> dict[Path, str]:
    from app.ontology.registry import get_registry

    data = get_registry().dump()
    return {
        WEB_ONTOLOGY_DIR / "concepts.generated.ts": render_concepts_ts(data),
        WEB_ONTOLOGY_DIR / "reasons.generated.ts": render_reasons_ts(data),
        WEB_ONTOLOGY_DIR / "concepts.snapshot.json": render_snapshot(data),
    }


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--check", action="store_true", help="exit 1 when any generated file is stale")
    args = parser.parse_args(argv)

    rendered = render_all()
    if args.check:
        stale = [p for p, content in rendered.items() if not p.exists() or p.read_text(encoding="utf-8") != content]
        if stale:
            for p in stale:
                print(f"STALE: {p.relative_to(REPO_ROOT)}", file=sys.stderr)
            print(
                "ontology codegen is out of date — run: cd apps/worker && "
                "uv run python scripts/gen_ontology.py",
                file=sys.stderr,
            )
            return 1
        print(f"ontology codegen up to date ({len(rendered)} files)")
        return 0

    WEB_ONTOLOGY_DIR.mkdir(parents=True, exist_ok=True)
    for p, content in rendered.items():
        p.write_text(content, encoding="utf-8")
        print(f"wrote {p.relative_to(REPO_ROOT)} ({len(content):,} bytes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
