"""Reason codes — the one vocabulary for "why is this a dash?" (Phase 0.3).

Every place Fondok declines to produce a figure used to say so in its own
words: ``"Pending analyst decision"`` (memo overrides), ``"Basis mismatch —
needs review"`` (variance), the ``str_forecast_unavailable`` source label
doing refusal duty (engine_runner), the NOI-pin notice (Projections), and
bare ``"—"`` literals in the exports. This module gives those refusals a
single closed enum so an engine, an export and the UI all mean the same
thing by the same code, and so the Methodology page can document the
vocabulary FROM the code rather than from prose.

Nothing migrates to it in Phase 0 — the enum, the :class:`Refusal` carrier
and :data:`REASON_META` are additive. From Phase 1 the TypeScript mirrors
(``packages/schemas-ts/src/index.ts`` and
``apps/web/src/lib/ontology/reasons.generated.ts``) are generated by
``apps/worker/scripts/gen_ontology.py``; until then they are hand-kept in
lockstep with this file.
"""

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import TypedDict
from uuid import UUID

from pydantic import BaseModel, ConfigDict


class ReasonCode(str, Enum):
    """Why a figure is shown as a dash instead of a value."""

    NO_DOCUMENT = "no_document"            # required document type not on the deal
    NO_SOURCE = "no_source"                # documents exist, no field resolves to the concept
    UNIT_UNKNOWN = "unit_unknown"
    PERIOD_MISMATCH = "period_mismatch"    # only a monthly/YTD slice where annual is required
    BASIS_MISMATCH = "basis_mismatch"      # >300% plausibility guard
    BASIS_EXCLUDED = "basis_excluded"      # market segment / OM history not admitted as a broker claim
    AWAITING_ANALYST = "awaiting_analyst"  # "Pending analyst decision"
    NEEDS_REVIEW = "needs_review"
    PIN_ACTIVE = "pin_active"              # noi_override_by_year / terminal_noi_override
    STR_UNAVAILABLE = "str_unavailable"
    NOT_KNOWABLE_AS_OF = "not_knowable_as_of"
    AS_OF_UNKNOWN = "as_of_unknown"
    STALE_RUN = "stale_run"
    ENGINE_SKIPPED = "engine_skipped"
    INCONCLUSIVE = "inconclusive"          # USALI scorer < 5 applicable rules
    NOT_APPLICABLE = "not_applicable"


class Refusal(BaseModel):
    """A typed "no value" — the code plus whatever context the refuser has.

    Carried wherever a value would otherwise be: on a provenance trace
    (``ValueTrace.reason`` holds just the code), in an export cell, in a
    variance row's technical detail.
    """

    model_config = ConfigDict(extra="forbid")

    code: ReasonCode
    # Free-text elaboration for the analyst (never a substitute for ``code``).
    detail: str | None = None
    # The ontology concept the refusal is about (e.g. ``"rooms_revenue"``).
    concept: str | None = None
    # The document the refusal was raised against, when there is one.
    document_id: UUID | None = None
    # When the condition began (e.g. the run that went stale).
    since: datetime | None = None


class ReasonMeta(TypedDict):
    """Presentation metadata for one :class:`ReasonCode`."""

    # Short human label (a few words) — what a badge or a legend row says.
    label: str
    # The glyph shown in place of the value. One glyph for every code today.
    ui: str
    # One plain sentence for a tester: what the code means and what it implies.
    explanation: str


# The single glyph every refusal renders as today. Codes may earn distinct
# glyphs later; the ``ui`` field exists so that change is data, not code.
REFUSAL_GLYPH = "—"

REASON_META: dict[ReasonCode, ReasonMeta] = {
    ReasonCode.NO_DOCUMENT: {
        "label": "No source document",
        "ui": REFUSAL_GLYPH,
        "explanation": (
            "The document type this figure needs (for example a T-12 or an OM) "
            "has not been uploaded to the deal."
        ),
    },
    ReasonCode.NO_SOURCE: {
        "label": "No matching field",
        "ui": REFUSAL_GLYPH,
        "explanation": (
            "Documents are on the deal, but none of their extracted fields "
            "resolves to this concept."
        ),
    },
    ReasonCode.UNIT_UNKNOWN: {
        "label": "Unit unknown",
        "ui": REFUSAL_GLYPH,
        "explanation": (
            "A value was found but its unit could not be established (for "
            "example an occupancy above 100), so it is not used."
        ),
    },
    ReasonCode.PERIOD_MISMATCH: {
        "label": "Period mismatch",
        "ui": REFUSAL_GLYPH,
        "explanation": (
            "Only a monthly or year-to-date slice exists where an annual figure "
            "is required, so nothing is compared."
        ),
    },
    ReasonCode.BASIS_MISMATCH: {
        "label": "Basis mismatch — needs review",
        "ui": REFUSAL_GLYPH,
        "explanation": (
            "The two figures are more than 300% apart, so they sit on different "
            "bases and are not compared as a variance."
        ),
    },
    ReasonCode.BASIS_EXCLUDED: {
        "label": "Not admitted as a broker claim",
        "ui": REFUSAL_GLYPH,
        "explanation": (
            "The row is a market-segment stat, an STR / CoStar reading or the "
            "OM's historical block, so it is not treated as the broker's claim."
        ),
    },
    ReasonCode.AWAITING_ANALYST: {
        "label": "Pending analyst decision",
        "ui": REFUSAL_GLYPH,
        "explanation": (
            "This figure is a recorded decision the analyst has not yet made or "
            "confirmed."
        ),
    },
    ReasonCode.NEEDS_REVIEW: {
        "label": "Needs review",
        "ui": REFUSAL_GLYPH,
        "explanation": (
            "A low-confidence read or a conflicting override is waiting on an "
            "analyst before the figure is used."
        ),
    },
    ReasonCode.PIN_ACTIVE: {
        "label": "NOI pinned",
        "ui": REFUSAL_GLYPH,
        "explanation": (
            "An analyst NOI schedule (noi_override_by_year / "
            "terminal_noi_override) is active, so the operating model's own "
            "figure is not shown."
        ),
    },
    ReasonCode.STR_UNAVAILABLE: {
        "label": "STR unavailable",
        "ui": REFUSAL_GLYPH,
        "explanation": (
            "STR rates were requested but could not populate (no STR Trend "
            "extraction, coverage too low or a loader failure); the model stays "
            "on the T-12 base."
        ),
    },
    ReasonCode.NOT_KNOWABLE_AS_OF: {
        "label": "Not knowable as of this date",
        "ui": REFUSAL_GLYPH,
        "explanation": (
            "The figure depends on information that did not exist as of the "
            "run's as-of date."
        ),
    },
    ReasonCode.AS_OF_UNKNOWN: {
        "label": "As-of date unknown",
        "ui": REFUSAL_GLYPH,
        "explanation": (
            "The reporting date of the source could not be established, so the "
            "figure cannot be placed in time."
        ),
    },
    ReasonCode.STALE_RUN: {
        "label": "Stale run",
        "ui": REFUSAL_GLYPH,
        "explanation": (
            "Inputs changed after the last engine run, or the run predates a "
            "figure the model now publishes; re-run the model to refresh this "
            "figure."
        ),
    },
    ReasonCode.ENGINE_SKIPPED: {
        "label": "Engine did not run",
        "ui": REFUSAL_GLYPH,
        "explanation": (
            "The engine that produces this figure was skipped or failed, so "
            "there is no output to show."
        ),
    },
    ReasonCode.INCONCLUSIVE: {
        "label": "Inconclusive",
        "ui": REFUSAL_GLYPH,
        "explanation": (
            "Fewer than 5 USALI rules applied to the statement, so a compliance "
            "score is not reported."
        ),
    },
    ReasonCode.NOT_APPLICABLE: {
        "label": "Not applicable",
        "ui": REFUSAL_GLYPH,
        "explanation": (
            "This figure does not apply to the deal as configured (for example "
            "a tranche that is not funded)."
        ),
    },
}


__all__ = [
    "REASON_META",
    "REFUSAL_GLYPH",
    "ReasonCode",
    "ReasonMeta",
    "Refusal",
]
