/**
 * reasons.generated.ts — hand-written for Phase 0; from Phase 1 generated by
 * apps/worker/scripts/gen_ontology.py — keep in sync.
 *
 * Source of truth: packages/schemas-py/fondok_schemas/reasons.py
 * (ReasonCode + REASON_META). The zod mirror lives in
 * packages/schemas-ts/src/index.ts; this file is the web app's dependency-free
 * copy so the Methodology page and (from Phase 1) every dash on the platform
 * read one vocabulary. Do not add codes here that the Python enum lacks.
 */

/** Why a figure is shown as a dash instead of a value. Order matches the Python enum. */
export const REASON_CODES = [
  'no_document', // required document type not on the deal
  'no_source', // documents exist, no field resolves to the concept
  'unit_unknown',
  'period_mismatch', // only a monthly/YTD slice where annual is required
  'basis_mismatch', // >300% plausibility guard
  'basis_excluded', // market segment / OM history not admitted as a broker claim
  'awaiting_analyst', // "Pending analyst decision"
  'needs_review',
  'pin_active', // noi_override_by_year / terminal_noi_override
  'str_unavailable',
  'not_knowable_as_of',
  'as_of_unknown',
  'stale_run',
  'engine_skipped',
  'inconclusive', // USALI scorer < 5 applicable rules
  'not_applicable',
] as const;

export type ReasonCode = (typeof REASON_CODES)[number];

/** Presentation metadata for one ReasonCode (mirror of fondok_schemas.reasons.ReasonMeta). */
export interface ReasonMeta {
  /** Short human label — what a badge or a legend row says. */
  label: string;
  /** The glyph shown in place of the value. One glyph for every code today. */
  ui: string;
  /** One plain sentence for a tester: what the code means and what it implies. */
  explanation: string;
}

/** The single glyph every refusal renders as today. */
export const REFUSAL_GLYPH = '—';

export const REASONS: Record<ReasonCode, ReasonMeta> = {
  no_document: {
    label: 'No source document',
    ui: REFUSAL_GLYPH,
    explanation:
      'The document type this figure needs (for example a T-12 or an OM) has not been uploaded to the deal.',
  },
  no_source: {
    label: 'No matching field',
    ui: REFUSAL_GLYPH,
    explanation:
      'Documents are on the deal, but none of their extracted fields resolves to this concept.',
  },
  unit_unknown: {
    label: 'Unit unknown',
    ui: REFUSAL_GLYPH,
    explanation:
      'A value was found but its unit could not be established (for example an occupancy above 100), so it is not used.',
  },
  period_mismatch: {
    label: 'Period mismatch',
    ui: REFUSAL_GLYPH,
    explanation:
      'Only a monthly or year-to-date slice exists where an annual figure is required, so nothing is compared.',
  },
  basis_mismatch: {
    label: 'Basis mismatch — needs review',
    ui: REFUSAL_GLYPH,
    explanation:
      'The two figures are more than 300% apart, so they sit on different bases and are not compared as a variance.',
  },
  basis_excluded: {
    label: 'Not admitted as a broker claim',
    ui: REFUSAL_GLYPH,
    explanation:
      "The row is a market-segment stat, an STR / CoStar reading or the OM's historical block, so it is not treated as the broker's claim.",
  },
  awaiting_analyst: {
    label: 'Pending analyst decision',
    ui: REFUSAL_GLYPH,
    explanation:
      'This figure is a recorded decision the analyst has not yet made or confirmed.',
  },
  needs_review: {
    label: 'Needs review',
    ui: REFUSAL_GLYPH,
    explanation:
      'A low-confidence read or a conflicting override is waiting on an analyst before the figure is used.',
  },
  pin_active: {
    label: 'NOI pinned',
    ui: REFUSAL_GLYPH,
    explanation:
      "An analyst NOI schedule (noi_override_by_year / terminal_noi_override) is active, so the operating model's own figure is not shown.",
  },
  str_unavailable: {
    label: 'STR unavailable',
    ui: REFUSAL_GLYPH,
    explanation:
      'STR rates were requested but could not populate (no STR Trend extraction, coverage too low or a loader failure); the model stays on the T-12 base.',
  },
  not_knowable_as_of: {
    label: 'Not knowable as of this date',
    ui: REFUSAL_GLYPH,
    explanation:
      "The figure depends on information that did not exist as of the run's as-of date.",
  },
  as_of_unknown: {
    label: 'As-of date unknown',
    ui: REFUSAL_GLYPH,
    explanation:
      'The reporting date of the source could not be established, so the figure cannot be placed in time.',
  },
  stale_run: {
    label: 'Stale run',
    ui: REFUSAL_GLYPH,
    explanation:
      'Inputs changed after the last engine run; re-run the model to refresh this figure.',
  },
  engine_skipped: {
    label: 'Engine did not run',
    ui: REFUSAL_GLYPH,
    explanation:
      'The engine that produces this figure was skipped or failed, so there is no output to show.',
  },
  inconclusive: {
    label: 'Inconclusive',
    ui: REFUSAL_GLYPH,
    explanation:
      'Fewer than 5 USALI rules applied to the statement, so a compliance score is not reported.',
  },
  not_applicable: {
    label: 'Not applicable',
    ui: REFUSAL_GLYPH,
    explanation:
      'This figure does not apply to the deal as configured (for example a tranche that is not funded).',
  },
};

/** True when `v` is one of the 16 reason codes (narrowing guard for API payloads). */
export function isReasonCode(v: unknown): v is ReasonCode {
  return typeof v === 'string' && (REASON_CODES as readonly string[]).includes(v);
}
