// AUTO-GENERATED by apps/worker/scripts/gen_ontology.py from
// apps/worker/app/ontology/concepts.yaml — DO NOT EDIT BY HAND.
// Regenerate: cd apps/worker && uv run python scripts/gen_ontology.py
// CI fails on drift: scripts/gen_ontology.py --check
/* eslint-disable */

/** One refusal code — why a value is a dash rather than a number. */
export interface ReasonMeta {
  label: string;
  ui: string;
  explanation: string;
}

export type ReasonCode = "no_document" | "no_source" | "unit_unknown" | "period_mismatch" | "basis_mismatch" | "basis_excluded" | "awaiting_analyst" | "needs_review" | "pin_active" | "str_unavailable" | "not_knowable_as_of" | "as_of_unknown" | "stale_run" | "engine_skipped" | "inconclusive" | "not_applicable";

export const REASON_CODES: readonly ReasonCode[] = [
  "no_document",
  "no_source",
  "unit_unknown",
  "period_mismatch",
  "basis_mismatch",
  "basis_excluded",
  "awaiting_analyst",
  "needs_review",
  "pin_active",
  "str_unavailable",
  "not_knowable_as_of",
  "as_of_unknown",
  "stale_run",
  "engine_skipped",
  "inconclusive",
  "not_applicable"
];

export const REASONS: Record<ReasonCode, ReasonMeta> = {
  "no_document": {
    "label": "No source document",
    "ui": "—",
    "explanation": "The document type this figure needs (for example a T-12 or an OM) has not been uploaded to the deal."
  },
  "no_source": {
    "label": "No matching field",
    "ui": "—",
    "explanation": "Documents are on the deal, but none of their extracted fields resolves to this concept."
  },
  "unit_unknown": {
    "label": "Unit unknown",
    "ui": "—",
    "explanation": "A value was found but its unit could not be established (for example an occupancy above 100), so it is not used."
  },
  "period_mismatch": {
    "label": "Period mismatch",
    "ui": "—",
    "explanation": "Only a monthly or year-to-date slice exists where an annual figure is required, so nothing is compared."
  },
  "basis_mismatch": {
    "label": "Basis mismatch — needs review",
    "ui": "—",
    "explanation": "The two figures are more than 300% apart, so they sit on different bases and are not compared as a variance."
  },
  "basis_excluded": {
    "label": "Not admitted as a broker claim",
    "ui": "—",
    "explanation": "The row is a market-segment stat, an STR / CoStar reading or the OM's historical block, so it is not treated as the broker's claim."
  },
  "awaiting_analyst": {
    "label": "Pending analyst decision",
    "ui": "—",
    "explanation": "This figure is a recorded decision the analyst has not yet made or confirmed."
  },
  "needs_review": {
    "label": "Needs review",
    "ui": "—",
    "explanation": "A low-confidence read or a conflicting override is waiting on an analyst before the figure is used."
  },
  "pin_active": {
    "label": "NOI pinned",
    "ui": "—",
    "explanation": "An analyst NOI schedule (noi_override_by_year / terminal_noi_override) is active, so the operating model's own figure is not shown."
  },
  "str_unavailable": {
    "label": "STR unavailable",
    "ui": "—",
    "explanation": "STR rates were requested but could not populate (no STR Trend extraction, coverage too low or a loader failure); the model stays on the T-12 base."
  },
  "not_knowable_as_of": {
    "label": "Not knowable as of this date",
    "ui": "—",
    "explanation": "The figure depends on information that did not exist as of the run's as-of date."
  },
  "as_of_unknown": {
    "label": "As-of date unknown",
    "ui": "—",
    "explanation": "The reporting date of the source could not be established, so the figure cannot be placed in time."
  },
  "stale_run": {
    "label": "Stale run",
    "ui": "—",
    "explanation": "Inputs changed after the last engine run, or the run predates a figure the model now publishes; re-run the model to refresh this figure."
  },
  "engine_skipped": {
    "label": "Engine did not run",
    "ui": "—",
    "explanation": "The engine that produces this figure was skipped or failed, so there is no output to show."
  },
  "inconclusive": {
    "label": "Inconclusive",
    "ui": "—",
    "explanation": "Fewer than 5 USALI rules applied to the statement, so a compliance score is not reported."
  },
  "not_applicable": {
    "label": "Not applicable",
    "ui": "—",
    "explanation": "This figure does not apply to the deal as configured (for example a tranche that is not funded)."
  }
};

export const REFUSAL_GLYPH = '—';

export function isReasonCode(v: unknown): v is ReasonCode {
  return typeof v === 'string' && (REASON_CODES as readonly string[]).includes(v);
}
