// AUTO-GENERATED by apps/worker/scripts/gen_ontology.py from
// apps/worker/app/ontology/concepts.yaml — DO NOT EDIT BY HAND.
// Regenerate: cd apps/worker && uv run python scripts/gen_ontology.py
// CI fails on drift: scripts/gen_ontology.py --check
/* eslint-disable */

/** One refusal code — why a value is a dash rather than a number. */
export interface ReasonMeta {
  label: string;
  ui: string;
  explanation: string;
}

export type ReasonCode = "no_document" | "no_source" | "unit_unknown" | "period_mismatch" | "basis_mismatch" | "basis_excluded" | "awaiting_analyst" | "needs_review" | "pin_active" | "str_unavailable" | "not_knowable_as_of" | "as_of_unknown" | "stale_run" | "engine_skipped" | "inconclusive" | "not_applicable";

export const REASON_CODES: readonly ReasonCode[] = [
  "no_document",
  "no_source",
  "unit_unknown",
  "period_mismatch",
  "basis_mismatch",
  "basis_excluded",
  "awaiting_analyst",
  "needs_review",
  "pin_active",
  "str_unavailable",
  "not_knowable_as_of",
  "as_of_unknown",
  "stale_run",
  "engine_skipped",
  "inconclusive",
  "not_applicable"
];

export const REASONS: Record<ReasonCode, ReasonMeta> = {
  "no_document": {
    "label": "No document",
    "ui": "No document",
    "explanation": "No document of the required type has been uploaded for this deal."
  },
  "no_source": {
    "label": "No source",
    "ui": "Not in documents",
    "explanation": "The uploaded documents do not carry this line under any known name."
  },
  "unit_unknown": {
    "label": "Unit unknown",
    "ui": "Unit unknown",
    "explanation": "A value was found but its unit could not be established, so it is not shown."
  },
  "period_mismatch": {
    "label": "Period mismatch",
    "ui": "Period mismatch",
    "explanation": "The only values found are for a different period (a month or quarter where an annual figure is needed)."
  },
  "basis_mismatch": {
    "label": "Basis mismatch",
    "ui": "Basis mismatch",
    "explanation": "The two figures are on different bases (a percent against a fraction, a month against a year) and are not compared."
  },
  "basis_excluded": {
    "label": "Basis excluded",
    "ui": "Excluded",
    "explanation": "The only values found are from an excluded basis (the OM’s history block, a comp-set stat, or market data) rather than the basis requested."
  },
  "awaiting_analyst": {
    "label": "Awaiting analyst",
    "ui": "Awaiting input",
    "explanation": "This value needs an analyst decision or input before it can be shown."
  },
  "needs_review": {
    "label": "Needs review",
    "ui": "Needs review",
    "explanation": "The extracted value is low-confidence or conflicts with another source and has not been reviewed."
  },
  "pin_active": {
    "label": "Pinned",
    "ui": "Pinned",
    "explanation": "An analyst pin holds a different value for this line."
  },
  "str_unavailable": {
    "label": "STR unavailable",
    "ui": "STR unavailable",
    "explanation": "STR rates were requested but no STR Trend extraction (or too little coverage) is available."
  },
  "not_knowable_as_of": {
    "label": "Not knowable as of date",
    "ui": "Not yet knowable",
    "explanation": "The value is dated after the as-of date of this view and cannot be known yet."
  },
  "as_of_unknown": {
    "label": "As-of date unknown",
    "ui": "Undated",
    "explanation": "The value carries no date, so it cannot be placed on the timeline."
  },
  "stale_run": {
    "label": "Stale run",
    "ui": "Stale",
    "explanation": "The last engine run predates the inputs that feed this value — re-run the model."
  },
  "engine_skipped": {
    "label": "Engine skipped",
    "ui": "Not run",
    "explanation": "The engine that produces this value did not run because an upstream engine failed."
  },
  "inconclusive": {
    "label": "Inconclusive",
    "ui": "Inconclusive",
    "explanation": "Too few applicable checks to state a result."
  },
  "not_applicable": {
    "label": "Not applicable",
    "ui": "N/A",
    "explanation": "This line does not apply to the deal (for example F&B on a select-service hotel)."
  }
};

export const REFUSAL_GLYPH = '—';

export function isReasonCode(v: unknown): v is ReasonCode {
  return typeof v === 'string' && (REASON_CODES as readonly string[]).includes(v);
}
